server:
  port: 4000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon
    username: user
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 250   # 200 동시접속 + 여유
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none  # or validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: coupon-group
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
